<?php

return [

    'states' => [
        'Andhra Pradesh' => 'Andhra Pradesh',
        'Arunachal Pradesh' => 'Arunachal Pradesh',
        'Assam' => 'Assam',
        'Bihar' => 'Bihar',
        'Chhattisgarh' => 'Chhattisgarh',
        'Goa' => 'Goa',
        'Gujarat' => 'Gujarat',
        'Haryana' => 'Haryana',
        'Himachal Pradesh' => 'Himachal Pradesh',
        'Jammu and Kashmir' => 'Jammu and Kashmir',
        'Jharkhand' => 'Jharkhand',
        'Karnataka' => 'Karnataka',
        'Kerala' => 'Kerala',
        'Madhya Pradesh' => 'Madhya Pradesh',
        'Maharashtra' => 'Maharashtra',
        'Manipur' => 'Manipur',
        'Meghalaya' => 'Meghalaya',
        'Mizoram' => 'Mizoram',
        'Nagaland' => 'Nagaland',
        'Odisha' => 'Odisha',
        'Punjab' => 'Punjab',
        'Rajasthan' => 'Rajasthan',
        'Sikkim' => 'Sikkim',
        'Tamil Nadu' => 'Tamil Nadu',
        'Telangana' => 'Telangana',
        'Tripura' => 'Tripura',
        'Uttarakhand' => 'Uttarakhand',
        'Uttar Pradesh' => 'Uttar Pradesh',
        'West Bengal' => 'West Bengal',
        'Andaman and Nicobar Islands' => 'Andaman and Nicobar Islands',
        'Chandigarh' => 'Chandigarh',
        'Dadra and Nagar Haveli' => 'Dadra and Nagar Haveli',
        'Daman and Diu' => 'Daman and Diu',
        'Delhi' => 'Delhi',
        'Lakshadweep' => 'Lakshadweep',
        'Puducherry' => 'Puducherry',
    ]    
];